### ISSUE TITLE
Lowercase headers support

### ISSUE THREAD

**Issue by xshadow0x** [reqable/reqable-app#902] opened 2024-09-04 08:55 UTC
**Describe the bug**
Bug occurs when sniffing traffic from some Android applications which send requests with headers in lowercase, such as "user-agent" instead of "User-Agent" (as the Dart/2.19 (dart
) client does, for example). In this case, reqable adds an additional "User-Agent" header, which overwrites the original lowercase header when sending the request or copying it as a curl command. In my case, this prevented the server from processing the request and returned a 403 error.

**Screenshots**
![image_2024-08-26_21-19-41](https://github.com/user-attachments/assets/bfacd4a3-ee10-470b-b75f-12936821d89a)
![image_2024-08-26_21-20-04](https://github.com/user-attachments/assets/552edffc-43ae-499d-9ab0-b0e2cc78ceac)

**Information**
 - Platform: windows, android
 - OS: win11, android14
 - Arch: win64, android arm64
 - App Version: v2.22.0

**Comment by MegatronKing** [comment] 2024-09-04 09:03
Thanks for your feedback. I don't think this bug is caused by the header uppercase, because the header name is not case sensitive.

**Comment by MegatronKing** [comment] 2024-09-05 13:09
I think it is a same issue like #901. I will close this due to #901 was fixed.

**Closed by MegatronKing** 2024-09-05 13:09 UTC
Labels: bug
