### ISSUE TITLE
[bug] Websocket not showing

### ISSUE THREAD

**Issue by MrIkso** [reqable/reqable-app#434] opened 2024-01-31 15:23 UTC
**Describe the bug**
Use android version with vpn mode and use app with websocket. App not recorded any web sockets

**Information**
 - Platform: android 
 - OS: 13
 - Arch: arm64
 - App Version: 2.6.0

**Comment by MegatronKing** [comment] 2024-01-31 15:51
@MrIkso Hello, I just confirmed a bug. If the value of `Connection` in the request header contains other values than `Upgrade`, such as `keep-alive, Upgrade`, it will not be recognized as a websocket. Can you confirm that this is the same issue?

**Comment by MrIkso** [comment] 2024-01-31 16:28
See video
https://github.com/reqable/reqable-app/assets/43380144/17f65416-2de0-4d46-9eba-6a344d32c6f0

**Comment by MrIkso** [comment] 2024-01-31 17:12
I think socket. I'm not sure exactly.

**Comment by MegatronKing** [comment] 2024-02-01 02:40
> I think socket. I'm not sure exactly.

Reqable only records HTTP and its derived protocols, but for raw socket protocol, it will not be recorded.

**Comment by MrIkso** [comment] 2024-02-01 05:21
> > I think socket. I'm not sure exactly.
> 
> Reqable only records HTTP and its derived protocols, but for raw socket protocol, it will not be recorded.

See my target [app](https://www.apkmirror.com/apk/4pda/4pda/4pda-1-9-42-release/)
Reqable say HTTP/1.1

**Comment by MegatronKing** [comment] 2024-02-02 09:41
> Reqable say HTTP/1.1

Do you have a new screen record? The previous shows the connection has a `993` port, not like a normal http protocol.

**Comment by MegatronKing** [comment] 2024-02-07 09:43
> > > Reqable say HTTP/1.1
> > 
> > 
> > Do you have a new screen record? The previous shows the connection has a `993` port, not like a normal http protocol.
> 
> I'm tested another capute app. Connection type IMAPS (TCP)

That make sense, 993 is the default port of IMAPS, this protocol is not supported by Reqable.

**Comment by MegatronKing** [comment] 2024-02-07 09:44
I will close this issue due to it is not a bug of Reqable.

**Closed by MegatronKing** 2024-02-07 09:44 UTC
Labels: bug, p0
