### ISSUE TITLE
[bug] NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by wontfuck** [reqable/reqable-app#676] opened 2024-05-24 09:00 UTC
NET::ERR_CERT_AUTHORITY_INVALID

Error after trying to install the ca magisk module, before that it was normal to use the root method.

Is there a solution? I have deleted the module and installed the root method again but the error persists, even though it was normal before. 

**Information**
 - Platform: Andoid
 - OS: Android 10
 - Arch: arm64
 - App Version: 2.16.1

**Comment by MegatronKing** [comment] 2024-05-28 12:41
Magisk should be worked, I don't known which caused your issue.

**Comment by czy1996** [comment] 2024-05-31 00:44
im new to this software, tried magisk method since the beginning and it didnt work.
have not tried other methods yet, but did a little research, seems the official magisk module is generated by this project 

WindSpiritSR/CustomCACert

maybe others like https://github.com/ys1231/MoveCertificate could work?

**Comment by MegatronKing** [comment] 2024-06-05 14:13
@czy1996 The official magisk module is forked from `WindSpiritSR/CustomCACert`,  please see #344. We have tested this module, it works.

**Comment by MegatronKing** [comment] 2024-06-05 14:15
I will close this issue due to the issue is not related to reqable.

**Closed by MegatronKing** 2024-06-05 14:15 UTC
Labels: bug

**Comment by InstantHotCocoa** [comment] 2024-10-24 06:33
@czy1996 I may have the same problem, which should be caused by the certificate not being installed to the user store. The evidence is, when the certificate is only installed to the user store, chrome will not report an error, while the magisk module only installs to the system store. Although chrome reports an error, xiaomi browser doesn't, and other apps also run normally. So I solved this problem by installing the user certificate first, and then installing the magisk module.

**Comment by MegatronKing** [comment] 2024-10-24 06:38
@InstantHotCocoa 

Chrome's CA certificate policy has been changing, and recent versions will ignore self-signed CA in system.

> Google includes or removes self-signed root CA certificates in the Chrome Root Store as it deems appropriate at its sole discretion. The selection and ongoing inclusion of CA certificates is done to enhance the security of Chrome and promote interoperability. CA certificates that do not provide a broad service to all browser users will not be added to, or may be removed from the Chrome Root Store. CA certificates included in the Chrome Root Store must provide value to Chrome end users that exceeds the risk of their continued inclusion.
Chrome maintains a variety of mechanisms to protect its users from certificates that put their safety and privacy at risk, and is prepared to use them as necessary. A Chrome Root Program Participant’s failure to follow the minimum requirements defined in this policy may result in the corresponding CA certificate’s removal from the Chrome Root Store, limitations on Chrome's acceptance of the certificates they issue, or other technical or policy restrictions.

See https://www.chromium.org/Home/chromium-security/root-ca-policy/#:~:text=Google%20includes%20or%20removes%20self,%5D%20google%20%5Bdot%5D%20com.

**Comment by akxgg** [comment] 2025-02-04 10:11
@czy1996 

I also faced the same issue, but I was able to solve it using [cert-fixer](https://github.com/pwnlogs/cert-fixer).

To fix the problem, follow these steps:

Install the cert-fixer module.
Export the certificate from the Reqable app and install it.
Reboot your device.
Install the Reqable Magisk module.
After doing this, everything worked fine for me.
